// <auto-generated />
using System;
using CrowdScore.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CrowdScore.Api.Data.Migrations
{
    [DbContext(typeof(CrowdScoreDbContext))]
    partial class CrowdScoreDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CrowdScore.Api.Models.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("EventDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Location")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("CrowdScore.Api.Models.Fight", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CardPosition")
                        .HasColumnType("integer");

                    b.Property<int>("EventId")
                        .HasColumnType("integer");

                    b.Property<int>("FighterAId")
                        .HasColumnType("integer");

                    b.Property<int>("FighterBId")
                        .HasColumnType("integer");

                    b.Property<int>("ScheduledRounds")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("FighterAId");

                    b.HasIndex("FighterBId");

                    b.HasIndex("EventId", "CardPosition")
                        .IsUnique();

                    b.ToTable("Fights", t =>
                        {
                            t.HasCheckConstraint("CK_Fights_DifferentFighters", "\"FighterAId\" <> \"FighterBId\"");

                            t.HasCheckConstraint("CK_Fights_PositiveCardPosition", "\"CardPosition\" > 0");

                            t.HasCheckConstraint("CK_Fights_PositiveScheduledRounds", "\"ScheduledRounds\" > 0");
                        });
                });

            modelBuilder.Entity("CrowdScore.Api.Models.Fighter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Country")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Nickname")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Fighters");
                });

            modelBuilder.Entity("CrowdScore.Api.Models.Fight", b =>
                {
                    b.HasOne("CrowdScore.Api.Models.Event", "Event")
                        .WithMany("Fights")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CrowdScore.Api.Models.Fighter", "FighterA")
                        .WithMany("FightsAsFighterA")
                        .HasForeignKey("FighterAId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CrowdScore.Api.Models.Fighter", "FighterB")
                        .WithMany("FightsAsFighterB")
                        .HasForeignKey("FighterBId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("FighterA");

                    b.Navigation("FighterB");
                });

            modelBuilder.Entity("CrowdScore.Api.Models.Event", b =>
                {
                    b.Navigation("Fights");
                });

            modelBuilder.Entity("CrowdScore.Api.Models.Fighter", b =>
                {
                    b.Navigation("FightsAsFighterA");

                    b.Navigation("FightsAsFighterB");
                });
#pragma warning restore 612, 618
        }
    }
}
